#!/bin/bash -e
# https://github.com/wowu/run

function task:test { ## Run the integration test suite (requires Docker)
  git submodule update --init --recursive
  ./test/bats/bin/bats test/
}

function task:lint { ## Run ShellCheck on the docker-rollout script
  shellcheck docker-rollout
}

function task:help { ## List available tasks
  awk -v pad=25 'BEGIN {FS="(\\(\\))? ({ )?[#][#] ?"} /^function task:.*\{ [#][#] ?/ {sub("function task:", "", $1); printf "\033[36m%-"pad"s\033[0m %s\n", $1 " \033[32m" $3, $2}' "$0"
}


# shellcheck disable=SC2145
task:"${@:-help}"
